name: Demo QA Test
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E on Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/intercept.cy.js
          config-file: cypress.config.js
          # start: npm start
